build-server-protocol/build-server-protocol

- docs/bsp.md
Clearly just an accidental omission.
> Corrected missing `def`s in source

- docs/bsp.md
- src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- src/main/scala/ch/epfl/scala/bsp/endpoints/Endpoints.scala
This information is critical to tie together sbt build targets to a
series of scala projects and to reconstruct the sbt meta build graph.
It also fixes a typo in the name of the function for
`dependencyResources` and clarifies the spec of build target identifier.
> Add `definedTargets` to the sbt build target

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/CompileResult.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/TestResult.java
- bsp4j/src/test/scala/tests/BloopSuite.scala
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- docs/bsp.md
Replaces the previous mechanism, whereby build tools implementing BSP
would use a BSP protocol error to signal failure in compilation or
testing. Now, this new mechanism will simplify the handling on the
client side.
Fixes #41.
> Add status code to compile and test

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/BuildServer.java
- bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/BuildServerCapabilities.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/InverseSourcesParams.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/InverseSourcesResult.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- bsp4s/src/main/scala/ch/epfl/scala/bsp/endpoints/Endpoints.scala
- docs/bsp.md
This new name makes the purpose of this endpoint clearer and also easier to talk and write about.
> Rename textDocument/buildTargets into buildTarget/inverseSources (fix #48)

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/PublishDiagnosticsParams.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- docs/bsp.md
The previous solution did not allow the client to handle the lifetime of
the diagnostics correctly. For example, when errors disappear in a
buffer, there is no way for the client to know that it should clean
them. Taking another approach in the lifetime handling brings us to
other problems like missing present warnings that are not present during
incremental compilation, see https://github.com/scalacenter/bloop/issues/696
After a discussion with Olafur, we have come up with the following
solution. Reset is a flag that allows servers to tell clients how they
should use the diagnostics. When `reset` is enabled, the behavior is the
same as in the Language Server Protocol. When it isn't enabled, it
allows the build tools to stream errors coming from, say, a compilation
run to the client and …
> Add `reset` to `buildTarget/publishDiagnostics`

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/TaskId.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- docs/bsp.md
When implementing the task id bits in bsp v2, I looked at the
specification and found it confusing.
This commit hopefully improves the explanation of `Task Id` and stresses
that the `id` must be unique.
> Improve explanation of `Task Id` section

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/RunParams.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- docs/bsp.md
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jGenerators.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jShrinkers.scala
This allows the client to customize the application execution request (e.g. by specifying the main class as a desired entry point)
Addresses #88
> include optional 'data' field in buildTarget/run request

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/RunParamsDataKind.java
- bsp4j/src/main/java/ch/epfl/scala/bsp4j/TestParamsDataKind.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
This specifies explicitly the data kind for `ScalaMainClass` and `ScalaTestParams`.
Just a thought: in the future it would be useful to have a single module with those constants to avoid duplication and potential discrepancies
> add data kinds for scala test params and scala main class 

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/SourcesItem.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- docs/specification.md
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jGenerators.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/mock/HappyMockServer.scala
A source set in Intellij has a property called packagePrefix so that if the source root is not located at root of package namespace it is know which package it belongs to.
For example:
for file `src/test/Test.scala` with content 
```
package test
class Test
```
If the source set directory is `/src/test`, we should set package prefix to `test`, otherwise Intellij would think that `test.Test` class is actually `_root_.Test`.
Related PRs for integration:
https://github.com/scalacenter/bloop/pull/1183
https://github.com/scalameta/metals/pull/1470
https://github.com/JetBrains/intellij-scala/pull/503
> Add packagePrefix to SourceItem

- readme.md
Tomasz and Lukasz are engineers at VirtusLab who have recently
contributed nice improvements to the BSP specifications along with
server/client implementation in Bloop, Metals and IntelliJ.  I'd like to
welcome them to the team to recognize their valuable contributions and so
they can merge PRs, help manage the issue tracker and trigger new
releases.
> Welcome Tomasz and Lukasz to the team!

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/JvmBuildServer.java
- bsp4j/src/main/java/ch/epfl/scala/bsp4j/JvmExtension.xtend
- bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/BuildServerCapabilities.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/JvmRunEnvironmentParams.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/JvmRunEnvironmentResult.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- bsp4s/src/main/scala/ch/epfl/scala/bsp/endpoints/Endpoints.scala
- docs/extensions/jvm.md
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jArbitrary.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jGenerators.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/mock/AbstractMockServer.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/mock/HappyMockServer.scala
- tests/src/test/scala/tests/MockSuite.scala
- tests/src/test/scala/tests/SerializationPropertySuite.scala
Mirror endpoint to jvmTestEnvironment - used to execute main class
from an external tool in the same way as BSP server is doing it
Follow up of https://github.com/build-server-protocol/build-server-protocol/pull/107#discussion_r375346983
> Add new `buildTarget/jvmRunEnvironment` endpoint

- docs/specification.md
c0a91ef875c2f708d0800e512e9bd4d1f10faec5 changed the language of code samples from Scala to TypeScript, but did not change the sentence that stated the language of code samples.
> Fix declared syntax of code listings

- docs/specification.md
I assume 'k' is a typo, since it's not specified anywhere.
> Remove 'k'

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/JavaBuildServer.java
- bsp4j/src/main/java/ch/epfl/scala/bsp4j/JavaExtension.xtend
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/JavacOptionsItem.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/JavacOptionsParams.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/JavacOptionsResult.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- bsp4s/src/main/scala/ch/epfl/scala/bsp/endpoints/Endpoints.scala
- docs/extensions/java.md
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jArbitrary.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jGenerators.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/mock/AbstractMockServer.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/mock/HappyMockServer.scala
- tests/src/test/scala/tests/MockSuite.scala
- tests/src/test/scala/tests/SerializationPropertySuite.scala
Added an extension to the protocol in order to support Java projects. In the light of developments with the implementation of [BSP in bazel](https://github.com/bazelbuild/bazel/pull/11766), there is a need for a better support of java only projects
> Add extension for java projects

- docs/extensions/jvm.md
It has been discovered that IntelliJ as a client requires the JDK to be provided instead of the JRE. It was also found that servers such as Bloop already provide this information. Since the JRE is insufficient to build the environment, me and @jastice are now proposing a change to the `JVMBuildTarget`, in order for it to return the JDK instead of the JRE
> Change JVM extension to require the JDK to be provided instead of the JRE

- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/client/TestClient.scala
There were several problems with the current output of errors by the testkit, namely that it didn't allow you to have a proper knowledge as to how they failed in some cases. Therefore I improved how that was portrayed to the user.
> Improve Testkit error visibility

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/BuildTargetTag.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/JavacOptionsParams.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- docs/specification.md
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jGenerators.scala
Add `manual` build target tag. This is based on the same manual tag in Bazel.
It is used when targets are not supposed to be considered by default when triggering a full workspace build. Instead a build/test/etc action on these targets should be triggered manually by the user.
> Add `manual` build target tag

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/BuildServer.java
- bsp4j/src/main/java/ch/epfl/scala/bsp4j/JavaExtension.xtend
- bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/BuildServerCapabilities.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/JavacOptionsParams.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- bsp4s/src/main/scala/ch/epfl/scala/bsp/endpoints/Endpoints.scala
- docs/bindings/java.md
- docs/specification.md
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jGenerators.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/mock/HappyMockServer.scala
- tests/src/test/scala/tests/TypoSuite.scala
The `reload` request instructs the build server to reload the build configuration.
This request should be supported by build tools that keep their state in memory.
If the `reload` request returns with an error, it's expected that other requests
respond with the previously known "good" state.
This request is motivated by tools such as sbt, which maintain an in-memory state of the build, where reloading the build on-demand is not considered practical.
Prompted by discussion in https://github.com/sbt/sbt/issues/5783
Solves #134 
cc @adpi2
> Introduce build/reload request

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/DebugSessionParamsDataKind.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
Extend `DebugSessionParamsDataKind` to support remote debugging.
Prerequisite of supporting remote debugging in bloop (and metals), see https://github.com/scalacenter/bloop/pull/1378
> Add support for remote debugging

- .github/workflows/release.yml
- .github/workflows/verify.yml
- project/build.properties
- project/plugins.sbt
- website/i18n/en.json
- website/package.json
- website/yarn.lock
I was looking for something on the website today that I knew existed and couldn't find it. It looks like the release CI has been failing for the last month, which explain why I couldn't find the `workspace/reload` stuff I was looking for. I'm not 100% sure why it's failing as the error isn't extremely descriptive. There does seem to be a json parsing issue, but the file it's reporting looks fine to me (sidebars.json). I do see some warnings about outdated stuff, so this is more of a stab at just updating the site generation stuff in hopes that it fixes the issue. If not, then at least this stuff is updated 🤷.
The first failure looks to be this one when @olafurpg moved the site release to GH actions, and the site release has failed ever since. …
> Update sbt-mdoc, docusaurus, and actions.

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/ScalaExtension.xtend
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/ScalaTestParams.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- docs/extensions/scala.md
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jGenerators.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jShrinkers.scala
Reasoning behind this is described in https://github.com/build-server-protocol/build-server-protocol/issues/143
I've taken changes from https://github.com/build-server-protocol/build-server-protocol/pull/96 and made them on latest master + made jvmOptions nullable.
> add jvm options to ScalaTestParams

- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/client/TestClient.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/client/mock/MockSession.scala
Removed logging of cancellation expections coming cancelling the server after tests were finished
Improved readability of testkit assertion related errors, by removing the `ExecutionException` layer and only throwing the assertion error, which improves readability of errors from
```
java.util.concurrent.ExecutionException: Boxed Error
ch.epfl.scala.bsp.testkit.client.TestFailedException: java.util.concurrent.ExecutionException: Boxed Error
(...)
```
to 
```
java.lang.AssertionError: assertion failed: Cleaned cache successfully, when it should have failed
ch.epfl.scala.bsp.testkit.client.TestFailedException: java.lang.AssertionError: assertion failed: Cleaned cache successfully, when it should have failed
(...)
```
> Improve testkit error readability

- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/UtilShrinkers.scala
Whenever generating paths with the testkit for clients, the shrinker for paths may get an empty string value. Whenever this was the case, the shrinker returned another empty string, leading to a cycle. This prevents that.
> Return empty stream on empty path

- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/UtilShrinkers.scala
Whenever a path is an empty string, the iterator returns has having a next. This is, apparently, undefined behavior. Here's an example of this:
> Path shrinker returning empty on empty string

- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/client/TestClient.scala
Found a bug on the options comparison of the scalac and javac options methods regarding the comparison of the options themselves.
> Fix scalac and javac options testkit methods

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/BuildServerCapabilities.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/BuildTargetCapabilities.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/DebugProvider.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- build.sbt
- docs/specification.md
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jGenerators.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jShrinkers.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/mock/HappyMockServer.scala
- tests/src/test/scala/tests/MockClientSuite.scala
- tests/src/test/scala/tests/SerializationSuite.scala
- tests/src/test/scala/tests/TypoSuite.scala
This attempts to address https://github.com/build-server-protocol/build-server-protocol/issues/145
Specifically, looking to improve how metals can support debug support: https://github.com/adpi2/metals/pull/1/files#diff-2249f2a7f1d0baedcc556404e0eb12adcd38f5fdb4d0d640d662643bc3de5b1fR514
TODO:
> Add debug provider to build server capabilities

- .gitignore
- bsp4j/src/main/java/ch/epfl/scala/bsp4j/BuildServer.java
- bsp4j/src/main/java/ch/epfl/scala/bsp4j/MavenExtension.xtend
- bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/BuildServerCapabilities.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/DependencyModule.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/DependencyModulesItem.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/DependencyModulesParams.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/DependencyModulesResult.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/MavenDependencyModule.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/MavenDependencyModuleArtifact.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- bsp4s/src/main/scala/ch/epfl/scala/bsp/endpoints/Endpoints.scala
- docs/bindings/java.md
- docs/extensions/maven.md
- docs/specification.md
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jGenerators.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jShrinkers.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/mock/HappyMockServer.scala
- tests/src/test/scala/tests/TypoSuite.scala
- website/i18n/en.json
Based on #164 proposal. 
Adds the new BSP method - `buildTarget/dependencyModules`
It's a kind of extended version of  `buildTarget/sources` that has attached metadata about dependency libraries.
The only difference with the original proposal is that all JVM-specific data (org, classifiers) from DependencyModule is moved into the JVM extension.
> Add `buildTarget/dependencyModules` BSP method

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/SbtExtension.xtend
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/SbtBuildTarget.java
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jGenerators.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jShrinkers.scala
The classpath had previously been removed from the `SbtBuildTarget` but it was still available through the constructor of the java version.
> Remove classpath from sbt build target

- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/client/TestClient.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/mock/HappyMockServer.scala
- tests/src/test/scala/tests/MockClientSuite.scala
- tests/src/test/scala/tests/MockSuite.scala
The client testkit didn't provide a means of testing the `data` field of the workspace build target. This PR aims to change that.
> Add data field comparisons to workspace build targets testkit

- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- bsp4s/src/main/scala/ch/epfl/scala/bsp/endpoints/Endpoints.scala
- build.sbt
- project/plugins.sbt
- tests/src/test/scala/tests/SerializationPropertySuite.scala
- tests/src/test/scala/tests/SerializationSuite.scala
- tests/src/test/scala/tests/TypoSuite.scala
- website/i18n/en.json
This is a continuation of the work that @jvican did in #125.
> Removes dependency on circe, we now only depend on jsoniter-scala itself
for JSON purposes, which is a library with no third-party dependencies.
I rebased on the current main branch and brought this up to date with the aim
to unlock #153.
~Note that that also includes the work in #174, so you may want to merge that in first.~
> Upgrade bsp4s to use jsonrpc4s and jsoniter-scala directly

- .github/workflows/verify.yml
- build.sbt
**NOTE** ~this is built on top of the work in https://github.com/build-server-protocol/build-server-protocol/pull/175, so you'll want to merge that in first. The only real changes are in this commit: https://github.com/build-server-protocol/build-server-protocol/pull/180/commits/e20a92adbbc875ccdd4c9946eac4f7d3ce45d53a~
Closes #153
> Cross build all Scala modules for 2.12.x and 2.13.x

- .git-blame-ignore-revs
- .github/workflows/verify.yml
- .scalafmt.conf
- CONTRIBUTING.md
- build.sbt
- project/plugins.sbt
So this is a bit opinionated, but I noticed there was a `.scalafmt.conf` file, but it wasn't enforced at all. This also resulted in quite a few different indentation styles throughout the Scala sources. This pr adds in the sbt-scalafmt plugin, runs it with the existing configuration, and adds a check into CI to enforce formatting.
I don't have strong opinions on the type of formatting at all, just strong feelings on using it and being consistent. So if you want something switched, let me know. Or if you don't want this enabled at all, let me know and I can just remove the `.scalafmt.conf` file.
Note that I also added an extra commit to add in the `.git-blame-ignore-revs`. I've been using this lately in projects where I add in formatting since it combats the "now my git blame is useless" …
> Enforce scalafmt

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/CompileReport.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- docs/specification.md
- tests/src/test/scala/tests/SerializationSuite.scala
This is meant to close #148 by adding in another field to the
`CompileReport` to signify to the client that the compilation was a
no-op. This is useful for some clients that trigger things based on
compliations, and they want to skip that trigger if the compilation was
a no-op. Currently this is accomplished by looking for keywords in the
message as is the case with Metals and Bloop.
> Add in `noOp` field to `CompileReport`.

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/Diagnostic.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jGenerators.scala
- tests/src/test/scala/tests/SerializationSuite.scala
Previously this was a single DiagnosticRelatedInformation that was
possible to be attached to a diagnostic. This change aligns it with the
[LSP spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnostic)
making this a `List[DiagnosticRelatedInformation]` instead.
Partly addresses #319
> fix: align DiagnosticRelatedInformation with the LSP spec

- build.sbt
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/client/TestClient.scala
I have tested this manually by tweaking the values hardcoded in HappyMockServer. The difference report looks like this:
```
[info] Property at path '/targets[BuildTarget [ \ id = BuildTargetIdentifier [ \ uri = "file:/tmp/bsp.MockClientSuite8802115287538715484/target1" \ ] \ displayName = "target 1" \ baseDirectory = "file:/tmp/bsp.MockClientSuite8802115287538715484/target1" \ tags = SeqWrapper ( \ "library" \ ) \ languageIds = SeqWrapper ( \ "scala" \ ) \ dependencies = EmptyList () \ capabilities = BuildTargetCapabilities [ \ canCompile = true \ canTest = false \ canRun = false \ canDebug = false \ ] \ dataKind = "scala" \ data = ScalaBuildTarget [ \ scalaOrganization = "org.scala-lang" \ scalaVersion = "2.12.7" \ scalaBinaryVersion = "2.12" \ platform = JVM \ jars = SeqWrapper ( \ …
```
> Use java-object-diff to compare WorkspaceBuildTargetsResult objects

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/BuildServer.java
- docs/bindings/java.md
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/mock/HappyMockServer.scala
- tests/src/test/scala/tests/TypoSuite.scala
This request is specified at https://build-server-protocol.github.io/docs/specification.html#debug-request
> feat: add `debugSession/start` request to `the BuildServer`

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/JvmExtension.xtend
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/JvmRunEnvironmentParams.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/JvmTestEnvironmentParams.java
- docs/extensions/jvm.md
Current documentation was outdated and it didn't reflect the actual shape of requests. Additionally, java classes lacked `originId` field - I added it with an additional constructor to not break compatibility.
For the reference this is what Scala classes looks like:
```scala
final case class JvmTestEnvironmentParams(
targets: List[BuildTargetIdentifier],
originId: Option[String]
)
final case class JvmEnvironmentItem(
target: BuildTargetIdentifier,
classpath: List[String],
jvmOptions: List[String],
workingDirectory: String,
environmentVariables: Map[String, String]
)
final case class JvmTestEnvironmentResult(
items: List[JvmEnvironmentItem]
)
```
> Small nitpicks regarding JVM environment requests

- .jvmopts
- bsp4j/src/main/java/ch/epfl/scala/bsp4j/DebugSessionParamsDataKind.java
- bsp4j/src/main/java/ch/epfl/scala/bsp4j/ScalaExtension.xtend
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/ScalaTestSuiteSelection.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/ScalaTestSuites.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
implements #249
There are only two scala build servers that implement debugging: bloop and sbt (I checked also mill and bazel-bsp). If this new kind is implemented in both of them then it'll be safe to add the new kind without any capability.
Progress with implementation:
> feat: add scala test selection request

- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/client/TestClient.scala
- tests/src/test/scala/tests/MockClientSuite.scala
Before:
```
[info]   Cause: java.lang.AssertionError: assertion failed: JVM Run Environment Items did not match! Expected: JvmRunEnvironmentResult [
[info]   items = SeqWrapper (
[info]     JvmEnvironmentItem [
[info]       target = BuildTargetIdentifier [
[info]         uri = "file:/tmp/bsp.MockClientSuite17070543597305035972/target1"
[info]       ]
[info]       classpath = SeqWrapper (
[info]         "scala-library.jar"
[info]       )
[info]       jvmOptions = SeqWrapper (
[info]         "-Xms256m"
[info]       )
[info]       workingDirectory = "/tmp"
[info]       environmentVariables = {A=a, TESTING=true}
[info]     ]
[info]   )
[info] ], got [JvmEnvironmentItem [
[info]   target = BuildTargetIdentifier [
[info]     uri = "file:/tmp/bsp.MockClientSuite17070543597305035972/target1" …
```
> Refactored some tests to make use of the java-object-diff library.

- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/client/TestClient.scala
- tests/src/test/scala/tests/MockClientSuite.scala
In PR #325, I have missed the negation in some of the test cases. These test cases broke after my refactoring, but these two bugs canceled each other, so that the build was still passing.
This pull request fixes those tests and refactors the remaining helper methods in `TestClient` to make use of the java-object-diff library.
> Fixed broken tests and refactored some more tests.

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/BuildServer.java
- bsp4j/src/main/java/ch/epfl/scala/bsp4j/OutputPathItemKind.java
- bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/BuildServerCapabilities.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/OutputPathItem.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/OutputPathsItem.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/OutputPathsParams.java
- bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/OutputPathsResult.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- bsp4s/src/main/scala/ch/epfl/scala/bsp/endpoints/Endpoints.scala
- docs/bindings/java.md
- docs/specification.md
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/client/TestClient.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jArbitrary.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jGenerators.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jShrinkers.scala
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/mock/HappyMockServer.scala
- tests/src/test/scala/tests/MockSuite.scala
- tests/src/test/scala/tests/SerializationPropertySuite.scala
- tests/src/test/scala/tests/TypoSuite.scala
This adds `outputDirectory` to BuildTarget to fix #205
> Fix #205: Add operation to get output paths

- docs/specification.md
This adds in `jvmRunEnvironmentProvider` and `jvmTestEnvironmentProvider` to the docs, which are currently missing from the `BuildServerCapabilities` documentation.
> docs: ensure all providers are mentioned in server capability docs

- .github/workflows/verify.yml
Alright you can see a working example of this in https://github.com/build-server-protocol/build-server-protocol/actions/runs/3875530094/jobs/6608192646. The idea here is that if you commit stuff without running `xtend` first you'll have changes in your Java files. When that happens, it will fail the build and we won't then test. This is meant to help avoid what happened in https://github.com/build-server-protocol/build-server-protocol/pull/414 where tests all pass and everything was green even though the new code wasn't generated.
> feat(ci): detect if there were file changes in CI when running `xtend`

- website/docusaurus.config.js
From looking at the failure in
https://github.com/build-server-protocol/build-server-protocol/actions/runs/3885907773/jobs/6630372169
it looks like we need `deploymentBranch` set. This change just adds
that.
> fix: ensure deployment works

- website/docusaurus.config.js
Since we use pages a bit different here and aren't actually following
the default `https://<org>.github.io/<repo>`, this is a hacky little way
to ensure that if for whatever reason someone goes through the
environments way in the repo to navigate to the site instead of just
clicking our url they'll actually get redirected to the right place.
> chore: redirect from `/build-server-protocol/` to `/`

- CONTRIBUTING.md
- website/docusaurus.config.js
- website/package.json
- website/yarn.lock
This replaces the current Algolia search (which doesn't work) with
`easyops-cn/docusaurus-search-local`, which seems to work pretty well.
We use this in
[Metals](https://github.com/scalameta/metals/pull/5066/files) as well,
which is what gave me the idea to switch it here seeing that it's
currently not working.
_You can see an example of this working here_
https://user-images.githubusercontent.com/13974112/227724242-1779cae8-acbf-476f-8257-2bbc4e56b907.mov
> refactor: switch from Algolia to a local search

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/feature_request.yml
- CONTRIBUTING.md
- readme.md
This is a PR that came about during the BSP discussions at the Scala
Tooling Summit. This change updates the README and the CONTRIBUTING doc
with some more relevant information about how this project is
maintained and also added some guidelines. It also adds a CODEOWNERS and
a feature request template.
> chore(governance): add in some basic things for maintenance

- docs/specification.md
Edit button is now on the bottom.
> fix(docs): update instructions on editing a page

- docs/specification.md
Update the BSP specification to clarify that servers should send `build/publishDiagnostics` with an empty diagnostics array to clear former diagnostics.
This change addresses the inconsistencies among various BSP servers and aligns the behavior with the Language Server Protoco, providing a more consistent experience for clients such as `scalameta/metals`.
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_publishDiagnostics
close https://github.com/build-server-protocol/build-server-protocol/issues/481
> docs: align BSP diagnostics clearing with LSP behavior

- .github/dependabot.yml
- .scala-steward.conf
Configure scala-steward and dependabot to do grouped dependency bump PRs on the first of each month. Generally this should be an appropriate interval as most updates are not time-critical. This change should decrease amount of notifications for maintainers somewhat.
> Less dependency bump PRs.

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/TaskFinishDataKind.java
- bsp4j/src/main/java/ch/epfl/scala/bsp4j/TaskProgressDataKind.java
- bsp4j/src/main/java/ch/epfl/scala/bsp4j/TaskStartDataKind.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- codegen/src/test/resources/DocsApprovalTest.bsp.approved.txt
- spec/src/main/resources/META-INF/smithy/bsp/bsp.smithy
- tests/src/test/scala/tests/SerializationSuite.scala
It makes more sense to keep these kinds separate
> Split TaskData into TaskStartData, TaskProgressData and TaskFinishData

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/DebugSessionParamsDataKind.java
- bsp4j/src/main/java/ch/epfl/scala/bsp4j/ScalaAttachRemote.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- codegen/src/test/resources/DocsApprovalTest.bsp.approved.txt
- codegen/src/test/resources/DocsApprovalTest.bsp.scala.approved.txt
- spec/src/main/resources/META-INF/smithy/bsp/extensions/scala.smithy
@ckipp01 @adpi2 could you please provide the description of this data kind? In the old doc [it wasn't very well documented](https://github.com/build-server-protocol/build-server-protocol/blob/v2.1.0-M4/docs/extensions/scala.md#scala-specific-data-kinds-for-debugging)
> Restore the scala-attach-remote data kind

- codegen/src/main/scala/bsp/codegen/bsp4s/ScalaRenderer.scala
Fortunately we currently don't have closed string enums in the spec, so it doesn't change the generated code
> Fix incorrect closed string enum rendering in bsp4s

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/DebugSessionParamsDataKind.java
- bsp4j/src/main/java/ch/epfl/scala/bsp4j/TestParamsDataKind.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- spec/src/main/resources/META-INF/smithy/bsp/extensions/scala.smithy
- website/generated/docs/extensions/scala.md
- website/generated/docs/specification.md
They were previously mistakenly marked as debug data kinds
> Fix "scala-test-suites" and "scala-test-suites-selection" data kinds

- spec/src/main/resources/META-INF/smithy/bsp/extensions/jvm.smithy
- website/generated/docs/extensions/jvm.md
hi,
one small (but important) change in the docs for `JvmBuildTarget` - imo it's the way how it should be used, or maybe I'm missing something here?
> `javaVersion` doc in `JvmBuildTarget` includes javac `-target` flag

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/BuildClientCapabilities.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
- spec/src/main/resources/META-INF/smithy/bsp/bsp.smithy
- website/generated/docs/specification.md
We can use this to make server aware if it's safe to deprecate the classpath in ScalacOptionsItem
> improvement: Add client capability for jvmCompileClasspathProvider

- bsp4j/src/main/java/ch/epfl/scala/bsp4j/JvmBuildServer.java
- bsp4s/src/main/scala/ch/epfl/scala/bsp/endpoints/Endpoints.scala
- spec/src/main/resources/META-INF/smithy/bsp/extensions/jvm.smithy
- testkit/src/main/scala/ch/epfl/scala/bsp/testkit/mock/HappyMockServer.scala
- website/generated/docs/extensions/jvm.md
It doesn't seem to be added by smithy, which I missed.
> bugfix: Add buildTarget/jvmCompileClasspath to JvmBuildServer and Scala's Endpoints

- .github/workflows/publish-docs.yml
- .github/workflows/release.yml
Artifacts should be released only when a new tag is marked, docs should be published on every push to master.
> Split docs publishing and releasing artifacts to maven
