build-server-protocol/build-server-protocol

readme.md

Justin has well earned his addition to the team, having implemented
almost the entirety of the BSP protocol in IntelliJ. His feedback has
been fundamental to improving the quality of the protocol.
Justin feel free to merge this PR if you're happy with this!

Welcome Justin to the team!

---

docs/bsp.md
src/main/scala/ch/epfl/scala/bsp/Bsp.scala

These changes will be shipped in M2.

Fix some oversights in the implementation

---

bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/CleanCacheResult.java
bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
docs/bsp.md

Follow up from https://github.com/scalacenter/bsp/pull/45#issuecomment-433389089
@jvican What do you think about renaming to `s/cleanCache/clean`?

Add optional message to CleanCacheResult

---

bsp4j/src/main/java/ch/epfl/scala/bsp4j/DataKind.java
bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
bsp4j/src/main/java/ch/epfl/scala/bsp4j/TaskDataKind.java
bsp4j/src/main/java/ch/epfl/scala/bsp4j/TestStatus.java
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/CompileTask.java
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/RunParams.java
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/TaskFinishParams.java
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/TaskProgressParams.java
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/TaskStartParams.java
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/TestFinished.java
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/TestStarted.java
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/TestTask.java
bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
docs/bsp.md

Fleshing out the proposal in #7, describe a spec for how task progress notifications work, and how they are used to communicate status in compile and test requests.

Describe task notifications and how they are used with requests

---

bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/BuildTarget.java
bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
docs/bsp.md

Add BuildTarget.baseDirectory

---

bsp4j/src/main/java/ch/epfl/scala/bsp4j/Connection.xtend
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/BspConnectionDetails.java
bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala

Include BspConnectionDetails in implementations

---

bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/CompileParams.java

Add missing CompileParams.arguments in bsp4j.

---

CONTRIBUTING.md

This *tries* to make it more clear how to make changes the protocol - by explicitly describing the workflow.

Describe the process of updating the protocol

---

bsp4j/src/main/java/ch/epfl/scala/bsp4j/DebugSessionParamsDataKind.java
bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/DebugSessionAddress.java
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/DebugSessionParams.java
bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
bsp4s/src/main/scala/ch/epfl/scala/bsp/endpoints/Endpoints.scala

This allows the client to run/debug code using the Debug Adapter Protocol

Add DAP capabilities to BSP

---

bsp4j/src/main/java/ch/epfl/scala/bsp4j/Protocol.xtend
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/BuildServerCapabilities.java
bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
testkit/src/main/scala/ch/epfl/scala/bsp/testkit/mock/HappyMockServer.scala

It was requested by @jastice here https://github.com/JetBrains/intellij-scala/pull/500#pullrequestreview-360335173

 Include JvmTestEnvironment in Build Server Capabilities

---

bsp4j/src/main/java/ch/epfl/scala/bsp4j/BuildTargetDataKind.java
bsp4j/src/main/java/ch/epfl/scala/bsp4j/JvmExtension.xtend
bsp4j/src/main/java/ch/epfl/scala/bsp4j/ScalaExtension.xtend
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/JvmBuildTarget.java
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/ScalaBuildTarget.java
bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
docs/extensions/jvm.md
docs/extensions/scala.md
testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jArbitrary.scala
testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jGenerators.scala
testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jShrinkers.scala
testkit/src/main/scala/ch/epfl/scala/bsp/testkit/mock/HappyMockServer.scala
tests/src/test/scala/tests/SerializationPropertySuite.scala
website/sidebars.json

This PR extends JvmEnvironmentItem with jdk (home uri and version string).
Also adds another endpoint jvmEnvironment (in addition to jvmTestEnvironment as generally this might be different.

Add buildTarget/jvmEnvironment endpoint

---

bsp4j/src/main/java/ch/epfl/scala/bsp4j/ScalaExtension.xtend
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/ScalaMainClass.java
bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
docs/extensions/scala.md
testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jGenerators.scala
testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/Bsp4jShrinkers.scala

The idea is having an ability for a user to provide environmet variables for starting a debug session.
Bloop Issue here: https://github.com/scalacenter/bloop/issues/1264

Change ScalaMainClass to carry environment variables

---

.github/workflows/verify.yml

Verify job that checks that xtend, mdoc, compile, package, test will run on pull requests.

Verify job

---

testkit/src/main/scala/ch/epfl/scala/bsp/testkit/client/ExpectedDiagnostic.scala
testkit/src/main/scala/ch/epfl/scala/bsp/testkit/client/TestClient.scala
testkit/src/main/scala/ch/epfl/scala/bsp/testkit/client/mock/BspError.scala
testkit/src/main/scala/ch/epfl/scala/bsp/testkit/client/mock/MockClient.scala
testkit/src/main/scala/ch/epfl/scala/bsp/testkit/client/mock/MockCommunications.scala
testkit/src/main/scala/ch/epfl/scala/bsp/testkit/client/mock/MockSession.scala
testkit/src/main/scala/ch/epfl/scala/bsp/testkit/mock/HappyMockServer.scala
tests/src/test/scala/tests/MockClientSuite.scala
tests/src/test/scala/tests/MockSuite.scala

Added a Testkit for the implementations of the server. The idea is to create a Mock Client in order to test several BSP features.
As of right now I am testing how it works against my [bsp implementation in bazel](https://github.com/andrefmrocha/bazel-bsp).
I also plan to add tests against the `HappyMockServer`.

Server Testkit

---

docs/specification.md

I missed that in https://github.com/build-server-protocol/build-server-protocol/pull/140!

update existing implementations in intro

---

testkit/src/main/scala/ch/epfl/scala/bsp/testkit/client/TestClient.scala
testkit/src/main/scala/ch/epfl/scala/bsp/testkit/client/mock/MockSession.scala
testkit/src/main/scala/ch/epfl/scala/bsp/testkit/mock/HappyMockServer.scala
tests/src/test/scala/tests/MockClientSuite.scala

Add several test methods for all current language specific extension methods, that is:
- `buildTarget/javacOptions`
- `buildTarget/jvmTestEnvironment` 
- `buildTarget/jvmRunEnvironment`
- `buildTarget/scalacOptions`
- `buildTarget/scalaTestClasses`
- `buildTarget/scalaMainClasses`

Teskit extensions

---

build.sbt
testkit/src/main/scala/ch/epfl/scala/bsp/testkit/gen/UtilShrinkers.scala

Fixes problems existing in the shrinkers of URIs, that caused them to launch several exceptions when used.

Fix generators

---

website/sidebars.json

The sidebar hasn't been updated with a few of the new extensions. This PR aims to change that!

Update docs sidebar

---

build.sbt

As of sbt 1.5.0 the old style syntax for sbt [has been
deprecated](https://eed3si9n.com/sbt-1.5.0). This fixes all the warning
when you start up sbt.
I also made a slight change to the `inferJavaHome()` method to ensure
that this compile as expected with both jdk 8 and 11.
I was looking at #153 and hit on these, so I figured I'd open a small separate pr for them.

Move to unified slash syntax for build.

---

build.sbt
tests/src/test/scala/tests/MockClientSuite.scala
tests/src/test/scala/tests/MockSuite.scala
tests/src/test/scala/tests/SerializationPropertySuite.scala
tests/src/test/scala/tests/SerializationSuite.scala
tests/src/test/scala/tests/TypoSuite.scala

This will fix the failures seen in the steward pr here: https://github.com/build-server-protocol/build-server-protocol/pull/195

Bump to latest scalatest

---

.github/workflows/verify.yml
.gitignore
build.sbt
project/plugins.sbt

The weird solution that was found by an accident.
Fixes #255

Fix for `bsp4j/xtend`

---

.scalafmt.conf
build.sbt

This will help with `publishLocal`.
Otherwise you will have to switch jdk versions. 11 for xtend and 8 for publish

[Build] `--release 8` for bsp4j

---

.jvmopts
bsp4j/src/main/java/ch/epfl/scala/bsp4j/ScalaExtension.xtend
bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/ScalaTestClassesItem.java
bsp4s/src/main/scala/ch/epfl/scala/bsp/Bsp.scala
docs/extensions/scala.md
tests/src/test/scala/tests/SerializationSuite.scala

feat: add optional framework field to scala test classes item

---

bsp4j/src/main/xtend-gen/ch/epfl/scala/bsp4j/JvmEnvironmentItem.java

It looks like previously extend wasn't ran meening that this was out of date a bit.

fix: ensure xtend was correctly ran

---

docs/faq.md

No such proto exists (anymore)

Remove reference to bsp.proto in FAQ

---

CONTRIBUTING.md

fixes https://github.com/build-server-protocol/build-server-protocol/issues/430

chore(docs): add in some release steps to the contributing docs

---

readme.md

followup to https://github.com/build-server-protocol/build-server-protocol/pull/465

@abrams27 as maintainer

---

CONTRIBUTING.md
build.sbt
codegen/src/main/scala/bsp/codegen/ir/SmithyToIR.scala
codegen/src/test/scala/DocsApprovalTest.docsAreApproved.approved.txt
codegen/src/test/scala/DocsApprovalTest.scala
codegen/src/test/scala/ExtensionApprovalTest.extensionIsApproved.cpp.approved.txt
codegen/src/test/scala/ExtensionApprovalTest.extensionIsApproved.java.approved.txt
codegen/src/test/scala/ExtensionApprovalTest.extensionIsApproved.jvm.approved.txt
codegen/src/test/scala/ExtensionApprovalTest.extensionIsApproved.maven.approved.txt
codegen/src/test/scala/ExtensionApprovalTest.extensionIsApproved.python.approved.txt
codegen/src/test/scala/ExtensionApprovalTest.extensionIsApproved.sbt.approved.txt
codegen/src/test/scala/ExtensionApprovalTest.extensionIsApproved.scala.approved.txt
spec/src/main/resources/META-INF/smithy/bsp/bsp.smithy

Approval tests ensure that we don't accidentally change the generated spec.

Add approval tests

---

codegen/src/main/scala/bsp/codegen/bsp4j/JavaRenderer.scala
codegen/src/main/scala/bsp/codegen/bsp4s/ScalaRenderer.scala

Use basepkg in generators

---

spec-traits/src/main/java/bsp/traits/DataKindTrait.java

Fix the DataKindTrait

---

.github/CODEOWNERS
website/generated/docs/bindings/java.md

So I'm no longer full-time at the Scala Center and honestly don't have
the time to do much here. I don't feel like my reviews add much on top
of what @adpi2 could just provide, so I'll remove myself from the
CODEOWNERS. If you do still want my feedback for anything, please feel
free to still ping me.

chore: remove me from CODEOWNERS

---

website/package.json
website/pnpm-lock.yaml

relevant discussion: https://github.com/cmfcmf/docusaurus-search-local/pull/218

fix docusaurus build
